# Generated by Django 4.2 on 2025-11-17 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import raffle.rooms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=120, unique=True)),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(choices=[('entry', 'Cargó Voucher'), ('register', 'Registro')], max_length=20)),
                ('reprint_count', models.PositiveSmallIntegerField(default=0)),
                ('room_id', models.PositiveSmallIntegerField(choices=[], default=1)),
            ],
            options={
                'ordering': ('-scanned_at',),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='PrinterConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(default='3nStar', max_length=120)),
                ('model', models.CharField(default='RPT006', max_length=120)),
                ('port', models.CharField(default='USB001', max_length=120)),
                ('vendor_id', models.CharField(default='0x0416', max_length=8)),
                ('product_id', models.CharField(default='0x5011', max_length=8)),
                ('queue_name', models.CharField(blank=True, default='POS-80', max_length=128)),
                ('paper_width_mm', models.PositiveSmallIntegerField(default=80)),
                ('theme_preference', models.CharField(choices=[('light', 'Tema claro'), ('dark', 'Tema oscuro')], default='light', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_name', models.CharField(default='Terminal principal', max_length=120)),
                ('current_room_id', models.PositiveSmallIntegerField(default=raffle.rooms.RoomDirectory.default_room_id)),
                ('terms_text', models.TextField(default='Al registrarse, acepta los términos y condiciones del sorteo.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='VoucherScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('room_id', models.PositiveSmallIntegerField(choices=[], default=1)),
                ('source', models.CharField(choices=[('entry', 'Cargó Voucher'), ('register', 'Registro')], max_length=20)),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_scans', to='raffle.person')),
            ],
            options={
                'ordering': ('-scanned_at',),
            },
        ),
        migrations.CreateModel(
            name='CouponSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.PositiveSmallIntegerField()),
                ('terminal_name', models.CharField(max_length=120)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('room_id', 'terminal_name'),
                'unique_together': {('room_id', 'terminal_name')},
            },
        ),
        migrations.CreateModel(
            name='CouponReprintLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.PositiveSmallIntegerField(default=1)),
                ('reprint_number', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reprint_logs', to='raffle.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_reprint_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CouponReprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.PositiveSmallIntegerField(choices=[], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reprint', to='raffle.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_reprints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='coupon',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='raffle.person'),
        ),
    ]
