# Generated by Django 5.2.8 on 2025-11-17 21:00

from django.db import migrations, models


def populate_terminal_metadata(apps, schema_editor):
    SystemSettings = apps.get_model("raffle", "SystemSettings")
    Coupon = apps.get_model("raffle", "Coupon")
    VoucherScan = apps.get_model("raffle", "VoucherScan")

    settings = SystemSettings.objects.order_by("id").first()
    terminal_name = settings.terminal_name if settings else "Terminal"

    Coupon.objects.filter(terminal_name="").update(terminal_name=terminal_name)
    VoucherScan.objects.filter(terminal_name="").update(terminal_name=terminal_name)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("raffle", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="terminal_name",
            field=models.CharField(default="", max_length=120),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="terminal_identifier",
            field=models.CharField(
                default="default-terminal", max_length=120, unique=True
            ),
        ),
        migrations.AddField(
            model_name="voucherscan",
            name="terminal_name",
            field=models.CharField(default="", max_length=120),
        ),
        migrations.RunPython(populate_terminal_metadata, noop_reverse),
    ]
