# Generated by Django 5.2.8 on 2025-11-17 21:21

import raffle.models.system
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raffle", "0002_coupon_terminal_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="company_name",
            field=models.CharField(default="Casinos Gala", max_length=120),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="coupon_legend",
            field=models.TextField(
                default="El Juego Compulsivo es Perjudicial para la Salud y Produce Adicción ley 6169"
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="operational_hours",
            field=models.JSONField(
                blank=True, default=raffle.models.system.default_operational_hours
            ),
        ),
    ]
