# Generated by Django 5.2.8 on 2025-11-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raffle", "0003_systemsettings_company_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="created_by_user",
            field=models.BooleanField(default=False),
        ),
    ]
