# Generated by Django 5.2.8 on 2025-11-21 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raffle", "0005_systemsettings_theme_preference"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="coupon",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_coupons",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="coupon",
            name="printed",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="coupon",
            name="source",
            field=models.CharField(
                choices=[
                    ("entry", "Cargó Voucher"),
                    ("register", "Registro"),
                    ("manual", "Ingreso manual"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="voucherscan",
            name="source",
            field=models.CharField(
                choices=[
                    ("entry", "Cargó Voucher"),
                    ("register", "Registro"),
                    ("manual", "Ingreso manual"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ManualCouponSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_id", models.PositiveSmallIntegerField()),
                ("last_number", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ("room_id",),
                "unique_together": {("room_id",)},
            },
        ),
    ]
