# Generated by Django 5.2.8 on 2025-11-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "raffle",
            "0006_coupon_created_by_coupon_printed_alter_coupon_source_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="room_ip",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
