# Generated by Django 5.2.8 on 2025-11-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_default_accounts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrador"),
                    ("cambista", "Cambista"),
                    ("jefesala", "Jefe de sala"),
                    ("user", "Operador (legado)"),
                ],
                default="cambista",
                max_length=20,
            ),
        ),
    ]
